# Generated by Django 5.0.1 on 2024-01-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Старая цена')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новая цена')),
                ('availibility', models.BooleanField(verbose_name='В наличии')),
                ('short_desc', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('long_desc', models.TextField(max_length=2000, verbose_name='Основное описание')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Длинна')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='Глубина')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('freshness_duration', models.CharField(max_length=40, verbose_name='Продолжительность свежести')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='URL')),
                ('is_sale', models.BooleanField(default=False)),
                ('product_pic', models.ImageField(upload_to='product_pic/%Y', verbose_name='Изображение')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='product.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category', verbose_name='Категория')),
            ],
        ),
    ]
