# Generated by Django 5.0.1 on 2024-01-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_color_options_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/%Y')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_pic',
        ),
        migrations.AddField(
            model_name='product',
            name='product_pic',
            field=models.ManyToManyField(related_name='product_images', to='product.productimages'),
        ),
    ]
