# Generated by Django 5.0.1 on 2024-01-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
