# Generated by Django 5.0.1 on 2024-01-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Список желаемого', 'verbose_name_plural': 'Списки желаемого'},
        ),
    ]
